# Generated by Django 5.2.17 on 2026-08-22 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_bodymeasurement_per_user_per_day'), models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='bodymeasurement_weight_positive'), models.CheckConstraint(condition=models.Q(('height__gt', 0)), name='bodymeasurement_height_positive'), models.CheckConstraint(condition=models.Q(('body_fat_percentage__gte', 0), ('body_fat_percentage__lte', 100)), name='bodymeasurement_bodyfat_in_range')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('age__gte', 0)), name='profile_age_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(max_length=55)),
                ('calories_burnt', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=55)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration__gt', 0)), name='workout_duration_positive'), models.CheckConstraint(condition=models.Q(('calories_burnt__gte', 0)), name='workout_calories_nonnegative')],
            },
        ),
    ]
