# Generated by Django 5.2.17 on 2026-08-27 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('trainee', 'Trainee')], default='trainee', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to=settings.AUTH_USER_MODEL),
        ),
    ]
