# Generated by Django 5.2.17 on 2026-08-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_profile_age_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodymeasurement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date']},
        ),
    ]
