# Generated by Django 5.2.17 on 2026-08-22 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('calories_per_100g', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fat_g', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'brand'), name='unique_food_name_brand'), models.CheckConstraint(condition=models.Q(('calories_per_100g__gte', 0)), name='food_calories_nonnegative'), models.CheckConstraint(condition=models.Q(('protein_g__gte', 0)), name='food_protein_nonnegative'), models.CheckConstraint(condition=models.Q(('carbs_g__gte', 0)), name='food_carbs_nonnegative'), models.CheckConstraint(condition=models.Q(('fat_g__gte', 0)), name='food_fat_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='LoggedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_items', to='nutrition.food')),
                ('logged_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.loggedmeal')),
            ],
            options={
                'ordering': ['food__name'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('quantity_g', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_meals', to='nutrition.food')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_meals', to='nutrition.mealplan')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='loggedmeal',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'meal_type'), name='unique_logged_meal_slot_per_user'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.UniqueConstraint(fields=('logged_meal', 'food'), name='unique_meal_item_per_logged_meal_and_food'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_g__gt', 0)), name='meal_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_mealplan_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='mealplan_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='plannedmeal',
            constraint=models.UniqueConstraint(fields=('meal_plan', 'food', 'planned_date', 'meal_type'), name='unique_planned_food_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='plannedmeal',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_g__gt', 0)), name='plannedmeal_quantity_positive'),
        ),
    ]
