# Generated by Django 5.2.17 on 2026-08-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loggedmeal',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='mealitem',
            options={'ordering': ['logged_meal']},
        ),
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='plannedmeal',
            options={'ordering': ['meal_type']},
        ),
    ]
