# Generated by Django 5.2.17 on 2026-08-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_loggedmeal_options_alter_mealitem_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='unique_food_name_brand'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('calories_per_100g__gte', 0)), name='food_calories_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('protein_g__gte', 0)), name='food_protein_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('carbs_g__gte', 0)), name='food_carbs_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('fat_g__gte', 0)), name='food_fat_nonnegative'),
        ),
    ]
