# Generated by Django 5.2.17 on 2026-08-22 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_food_unique_food_name_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealitem',
            options={'ordering': ['food__name']},
        ),
        migrations.AddConstraint(
            model_name='loggedmeal',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'meal_type'), name='unique_logged_meal_slot_per_user'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.UniqueConstraint(fields=('logged_meal', 'food'), name='unique_meal_item_per_logged_meal_and_food'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_g__gt', 0)), name='meal_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='mealplan_end_after_start'),
        ),
    ]
